### ISSUE TITLE
logstash-input-twitter 2.2 Nomethod error but use_samples => true returns tweets

### ISSUE THREAD

**Issue by mobcdi** [logstash-plugins/logstash-input-twitter#35]
Using the latest versions of ELK and the Logstash twitter input plugin I get the error below but if I include use_samples=> true in my logstash config my index is created for the 1st time and tweets populated. 

I also edited my config file to exclude my twitter api consumer key but still included `use_samples => true` and that returned expected authentication error messages indicating to me that when the consumer key was listed the `use_samples` was able to authenticate to twitter using the key,secret,token and token secret I provide indicating its not an issue with my twitter app details  

`{:timestamp=>"2015-12-10T21:38:28.394000+0000", :message=>"", :exception=>Twitter::Error::Unauthorized, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete'", "org/ruby_http_parser/RubyHttpParser.java:370:in `<<'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:16:in `<<'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:31:in `stream'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn}`

**Comment by mobcdi** [comment]
There are also entries in the log about undefined method filer for nil.NilClass.
Given my selected tags and accounts aren't massively popular at the moment could this be a case of the error handling missing Nil, none or no values being returned from the stream?

`{:timestamp=>"2015-12-10T21:39:21.426000+0000", :message=>"undefined method `filter' for nil:NilClass", :exception=>#<NoMethodError: undefined method `filter' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn}`

**Comment by aneveu** [comment]
I'm facing the same issue and I know for sure it's not coming from my credentials as I'm using them in two other configuration files and it works perfectly.

The only differences with the last one is that I'm using `follows` instead of `keywords` as I want to retrieve the twitter feed from an account and not only from tags.

Here is the input part of my configuration file:
`input {
twitter {
consumer_key => "xxx"
consumer_secret => "xxx"
oauth_token => "xxx"
oauth_token_secret => "xxx"
follows => [ "@elastic" ]
full_tweet => true
}
}`

And here is my stacktrace:

`{:exception=>Twitter::Error::Unauthorized, :backtrace=>["/Users/audrey/Dev/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:21:inon_headers_complete'", "org/ruby_http_parser/RubyHttpParser.java:370:in <<'", "/Users/audrey/Dev/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:16:in<<'", "/Users/audrey/Dev/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:31:in stream'", "/Users/audrey/Dev/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:inrequest'", "/Users/audrey/Dev/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in filter'", "/Users/audrey/Dev/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:inrun'", "/Users/audrey/Dev/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:206:in inputworker'", "/Users/audrey/Dev/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:199:instart_input'"], :options=>nil, :level=>:warn}`

Perhaps I'm not using the `follows` attribute the right way? I've tried with or without the `@` before the id but it makes no difference.

I've also tried to add use_samples => true as mentionned by @mobcdi and it works but indexed tweets are not relevant.

**Comment by awislowski** [comment]
I have same problem with logstasg 2.3.0 version.
only follows parameter for the plugin is not working.

**Comment by wathmal** [comment]
when you are using "follows" parameter you need to include **twitter user's ID instead of user name or screen name.**

you can use [this site](http://gettwitterid.com/) to grab relevant twitter id to username or twitter API.

`follows => ["372841707"]`
will do the fix for you.

**Comment by HawkieNorway** [comment]
What is the right syntax for a comma separated list?
follows => ["372841707","123456743"]
or
follows => ["372841707,123456743"]

**Comment by tinyMrChaos** [comment]
Hi, 

I just ran into this problem aswell and while just throwing things at the wall I discovered that adding language to the configuration fixes the Unathorized error

`languages          => ["en"]`

Devs might be able to figure out why but in the mean time, it should help a few.
