### ISSUE TITLE
Periodic EOFError issue

### ISSUE THREAD

**Issue by gmoskovicz** [logstash-plugins/logstash-input-twitter#39]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: 2.x
- Operating System: Linux
- Config File (if you have sensitive info, please remove it): -
- Sample Data: - 
- Steps to Reproduce: `nohup /usr/local/logstash/bin/logstash -f twitter.conf &`

Periodically, you get the following exception:

```
{
 :timestamp=>"2016-05-03T18:52:43.058000+0200",
 :message=>"End of file reached", 
 :exception=>#<EOFError: End of file reached>, 
 :backtrace=>[
    "org/jruby/ext/openssl/SSLSocket.java:777:in `sysread'",
    "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.13-java/lib/jopenssl19/openssl/buffering.rb:121:in `readpartial'", 
    "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter/patches.rb:31:in `stream'", 
    "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter/patches.rb:58:in `request'", 
    "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", 
    "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter.rb:128:in `run'", 
    "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:336:in `start_input'"], 
 :options=>nil, 
 :level=>:warn
}
```

**Comment by pratheekrebala** [comment]
+1

**Comment by aendrew** [comment]
I'm getting this too in 3.0.3, mainly following user streams.

**Comment by soukron** [comment]
+1 in logstash 6.2.1 with logstash-input-twitter 3.0.7
