### ISSUE TITLE
Issue with connection message=>"no address for stream.twitter.com"

### ISSUE THREAD

**Issue by prof-schacht** [logstash-plugins/logstash-input-twitter#57]
Hi

I have an issue with the input twitter plugin:
I'm using the official logstash docker container 6.1.3 from elastic . Created a Basic Pipelinefile as follow:

input {
  twitter {
    id => "id1"
    consumer_key => "" 
    consumer_secret => ""
    oauth_token => ""
    oauth_token_secret => ""
    keywords => ["news"]
    languages => ["en", "de"]
  }
}

output {
  mongodb {
    id => "id2"
    uri => "mongodb://xxxx:27017"
    database => "news"
    collection => "tweets"
  }
}

But when I start logstash I get the following error for this pipeline file:

[2018-02-01T09:02:54,649][WARN ][logstash.inputs.twitter  ] Twitter client error {:message=>"no address for stream.twitter.com", :exception=>"Resolv::ResolvError", :backtrace=>["/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:101:in `getaddress'", "/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:51:in `getaddress'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-twitter-3.0.7/lib/logstash/inputs/twitter/patches.rb:26:in `stream'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-twitter-3.0.7/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-twitter-3.0.7/lib/logstash/inputs/twitter.rb:138:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:524:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:517:in `block in start_input'"], :options=>nil}

Did somebody have an idea what I have to change to get this working. 
We are not behind a proxy. A ping from the docker host pc to stream.twitter.com resolves the address just fine. 

Thanks for your help.
BR

**Comment by prof-schacht** [comment]
Posted this on: https://discuss.elastic.co/t/issue-with-connection-message-no-address-for-stream-twitter-com/117983

As I think it is the better location for the problem.
